spring:
  application:
    name: worker
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest
    listener:
      ack-mode: record

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  enrichment:
    product-api:
      base-url: ${PRODUCT_API_URL}
    customer-api:
      base-url: ${CUSTOMER_API_URL}
